---
title: "Lab2"
author: "Nathanael Reese"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Task 1
#### Task 1a
```{r}
getwd()
```
## Task 2
#### Task 2a
```{r}
mpg.df <- read.csv("EPAGAS.csv")
head(mpg.df)
```
## Task 3
#### Task 3a
```{r}
mpg <- mpg.df$MPG
```

#### Task 3b
```{r}
z <- (mpg-mean(mpg))/sd(mpg)
mean(z)
```
*Mean of Z is close to zero so we can assume the statement is true*

#### Task 3c - Possible Outliers

```{r}
# Find the z values greater than 3 in size
z[abs(z)>3]

# Find the I values corresponding to these z values
mpg[abs(z)>3]

# Find the values of z that are possible outliers
z[abs(z)>=2 & abs(z)<=3]

#Find the values of MPG which are possible outliers
 mpg[abs(z)>=2 & abs(z)<=3]

```

#### Task 3d - Defined Outliers

```{r}
z[abs(z)>3]
mpg[abs(z)>3]
```

#### Task 3e - Show possible and defined outliers

```{r}
# Plot the outliers in red and the possible outliers in blue
mycol = ifelse(abs(z)>3, "Red",
        ifelse(abs(z)>=2 &abs(z)<=3,"Blue", "Black"))  

#Plot points with different plotting shapes        
mypch = ifelse(abs(z)>3, 20,
        ifelse(abs(z)>=2 &abs(z)<=3,21, 22))

#Use an installed library 
# You will need to install the "lattice" package -- unless using the Lab computers
#In R go to Packages   -- select "install packages" choose a mirror and then the "lattice" package
# Now issue the following commands
library(lattice)
dotplot(mpg,col=mycol)
```


## Task 4

#### Task 4a - Boxplot of MPG
```{r}
library(lattice)
boxplot(mpg,col="Black",data=mpg.df, notch=TRUE, horizontal = TRUE)
title("Miles Per Gallon")
```

#### Task 4b - Chebyshev
```{r}
length(mpg[abs(z)<3])/length(mpg)

## What is actually the case?
length(mpg[abs(z)<2])/length(mpg)

length(mpg[mean(mpg)-2*sd(mpg) < mpg & mpg < mean(mpg)+ 2*sd(mpg) ])/length(mpg)

classrange=45.0-29.9
inc=classrange/10
bins=seq(29.9,45.0,by=inc)
bins
with(mpg.df,cut(MPG,bins))
cl= with(mpg.df,cut(MPG,bins))
cl.tab=table(cl)
cl.tab
barplot(cl.tab)
mpg.df$MPG->mpg
length(mpg)

n=length(mpg)
barplot(cl.tab,las=2,main="Frequency Histogram",ylab="Frequency",space=0)
barplot(cl.tab/n,las=2,main="Relative Frequency Histogram",ylab="Relative frequency",space=0)
barplot(cl.tab/(n*inc),las=2,main="Density Histogram",ylab="Density",space=0)
```